name: WASM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  wasm:
    name: Build, lint, test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install stable toolchain
        run: rustup install

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '20'

      - name: Install wasm-pack
        uses: taiki-e/install-action@3235f8901fd37ffed0052b276cec25a362fb82e9 # v2.77.7
        with:
          tool: wasm-pack

      - name: Build with wasm-pack
        working-directory: tasm-lib
        run: wasm-pack build --release --target nodejs

      - name: Run wasm-pack tests
        working-directory: tasm-lib
        run: wasm-pack test --node
